name: focusguard
description: "A Flutter application that helps users stay focused by monitoring their device's motion and sending notifications when they are not moving for a certain period of time. The app uses the sensors_plus package to access the device's accelerometer and gyroscope data, and the flutter_local_notifications package to send local notifications. The app also uses shared_preferences to store user settings and sqflite to store historical data about the user's focus sessions."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  sensors_plus: ^6.1.2
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^18.0.1
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#012332"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_foreground_inset: 25
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
